// <auto-generated />
namespace Aplicacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Empleado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Empleado));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251515357_Empleado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
